name: hushflow_flutter
description: Hushflow - Your intelligent email subscription manager.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Serverpod
  serverpod_flutter: 1.2.6
  hushflow_client:
    path: ../hushflow_client

  # State Management
  flutter_riverpod: ^2.3.6

  # UI Components
  flex_color_scheme: ^8.0.0
  flutter_staggered_grid_view: ^0.7.0

  # Navigation
  go_router: ^10.0.0

  # Local Storage
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0

  # Auth
  google_sign_in: ^6.1.4

  # Network
  http: ^1.1.0

  # Audio
  just_audio: ^0.9.34
  audio_session: ^0.1.16

  # Sensors
  sensors_plus: ^3.0.3

  # Speech
  speech_to_text: ^6.3.0

  # Utils
  intl: ^0.18.1
  timeago: ^3.5.0
  url_launcher: ^6.1.12

  # Icons
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
