# This file contains environment variable placeholders for production deployment.
# It is safe to commit this file as it contains no actual secrets.
# During Docker build, this file should be copied to config/passwords.yaml

development:
  # Included for completeness, but typically not used in production Docker image
  database: '${DB_PASSWORD}'
  redis: '${REDIS_PASSWORD}'
  serviceSecret: '${SERVICE_SECRET}'
  gmailClientId: '${GMAIL_CLIENT_ID}'
  gmailClientSecret: '${GMAIL_CLIENT_SECRET}'
  gmailRedirectUri: '${GMAIL_REDIRECT_URI}'
  openaiApiKey: '${OPENAI_API_KEY}'

staging:
  database: '${DB_PASSWORD}'
  redis: '${REDIS_PASSWORD}'
  serviceSecret: '${SERVICE_SECRET}'
  gmailClientId: '${GMAIL_CLIENT_ID}'
  gmailClientSecret: '${GMAIL_CLIENT_SECRET}'
  gmailRedirectUri: '${GMAIL_REDIRECT_URI}'
  openaiApiKey: '${OPENAI_API_KEY}'

production:
  database: '${DB_PASSWORD}'
  redis: '${REDIS_PASSWORD}'
  serviceSecret: '${SERVICE_SECRET}'
  gmailClientId: '${GMAIL_CLIENT_ID}'
  gmailClientSecret: '${GMAIL_CLIENT_SECRET}'
  gmailRedirectUri: '${GMAIL_REDIRECT_URI}'
  openaiApiKey: '${OPENAI_API_KEY}'
